application: sonal-raj
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# making index.html as default page for root
- url: /
  static_files: www/index.html
  upload: www/index.html
  
# begin any static files request from www folder
- url: /
  static_dir: www